import type { Round } from "./types";

export const rounds: Round[] = [
  {
    id: 1,
    title: "Черная дыра",
    url: "https://youtu.be/XshcPNtDn-U",
    start: 21,
    end: 30.25,
    lyrics: [
      { id: 1, text: "Стебусь над школьницами, это заводит" },
      { id: 2, text: "Представляю чётко, чем всё это кончится" },
      { id: 3, text: "Как моя ракетница входит в твоё депо" },
      { id: 4, text: "Здесь только два варианта" },
      { id: 5, text: "Откуда в жопе бриллианты?" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 2,
    title: "В аквапарке",
    url: "https://youtu.be/6MsdmkSXoko?list=PLckdJPvgZ_PryFYJjwFHqR5nCH6D7ejdL",
    start: 23,
    end: 29,
    lyrics: [
      { id: 1, text: "В аквапарке реально охуенно, реально охуенно" },
      { id: 2, text: "Ну реально правда охуенно" },
      { id: 3, text: "В аквапарке горки, джакузи, ванны и фонтан" },
      { id: 4, text: "С детьми были там вчера" },
    ],
    hintLineIds: [1, 2],
    revealLineIds: [3, 4],
  },
  {
    id: 3,
    title: "Ебу закон",
    url: "https://youtu.be/t7kxt6IP-y4",
    start: 12,
    end: 20.5,
    lyrics: [
      { id: 1, text: "С мусорами разговариваю шёпотом" },
      { id: 2, text: "Некий Урал достаёт из карманов что-то" },
      { id: 3, text: "За шторой гусёк суёт девке гондон свой" },
      { id: 4, text: "Я снова заснул с Олей, а проснулся с Колей" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 4,
    title: "Ебу закон",
    url: "https://youtu.be/t7kxt6IP-y4",
    start: 34.5,
    end: 45.5,
    lyrics: [
      { id: 1, text: "Здесь играет биток, но не слышно басок" },
      { id: 2, text: "Косяк засох" },
      { id: 3, text: "Уральский насвай сплёвывает Васёк." },
      { id: 4, text: "На кассете Некий" },
      { id: 5, text: "Тут Кальмар ковыряется в заднем отсеке." },
      { id: 6, text: "Техник Паша - гомосек" },
    ],
    hintLineIds: [1, 2, 3, 4, 5],
    revealLineIds: [6],
  },
  {
    id: 5,
    title: "Море или океан",
    url: "https://youtu.be/w1KyP57F9RY",
    start: 109.5,
    end: 119,
    lyrics: [
      { id: 1, text: "Тебе придется расстаться с паспортом" },
      { id: 2, text: "Сейчас не плохо бы просто здесь остаться" },
      { id: 3, text: "Ну а что потом? Потом снова в сонное царство!" },
      { id: 4, text: "На столе явства" },
      { id: 5, text: "У меня не встал на тебя, хотя я даже не в мясо" },
      { id: 6, text: "Просто чё-то барахлит с возрастом колбаса" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5, 6],
  },
  {
    id: 6,
    title: "Гитлер",
    url: "https://youtu.be/sWRUMbToUOQ",
    start: 81.5,
    end: 89.5,
    lyrics: [
      { id: 1, text: "Сходу соснул у паралимпийца" },
      { id: 2, text: "Старичок засунул кулак в анус" },
      { id: 3, text: "По гробам хуём баунс" },
      { id: 4, text: "Половая губа шепчет: «Трахай»" },
      { id: 5, text: "Хорватия, хватит ебать страусов" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 7,
    title: "Это жизнь",
    url: "https://youtu.be/OIczpsRHxwM",
    start: 3,
    end: 6,
    lyrics: [
      { id: 1, text: "Куча пенисов упирается мне в лицо" },
      { id: 2, text: "Я не вижу где яйца, но лижу мошонку" },
      { id: 3, text: "Его семя как сгущёнка" },
      { id: 4, text: "Да похуй" },
      { id: 5, text: "Прыгай в моё лоно" },
      { id: 6, text: "Пиздатое порно, рвутся гандоны" },
    ],
    hintLineIds: [1],
    revealLineIds: [2, 3, 4, 5, 6],
  },
  {
    id: 8,
    title: "Не прут колеса",
    url: "https://youtu.be/NOuIXUmFc3g",
    start: 27,
    end: 37,
    lyrics: [
      { id: 1, text: "У коровы есть вымя, не доёбывай меня" },
      { id: 2, text: "Большой хуй у коня (Что?)" },
      { id: 3, text: "У меня конечно поменьше" },
      { id: 4, text: "Я ебал не много женщин" },
      { id: 5, text: "Точнее шесть, не больше и не меньше" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 9,
    title: "За кем стоит Андерграунд",
    url: "https://youtu.be/1hnqwsui5HE",
    start: 54.5,
    end: 61.5,
    lyrics: [
      { id: 1, text: "Меня от соли накрыло" },
      { id: 2, text: "Меня от соли накрыло" },
      { id: 3, text: "Я с Лефортово" },
      { id: 4, text: "У меня вот до сюда шорты" },
      { id: 5, text: "Если выше, то пидор" },
      { id: 6, text: "Если ниже, то гнида" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4, 5, 6],
  },
  {
    id: 10,
    title: "Заебись",
    url: "https://youtu.be/A0b3o5EejdM",
    start: 77,
    end: 85,
    lyrics: [
      { id: 1, text: "Я как будто кит, тебя оплодотворяю под этот хит" },
      { id: 2, text: "У меня пакет, в нем пачка оптимы и кент" },
      { id: 3, text: "Заваривай, блядина, горит резина" },
      { id: 4, text: "Мент пытался отъебать гориллу" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 11,
    title: "Блевбургер",
    url: "https://youtu.be/xQrKtfc77Lc",
    start: 0,
    end: 3.5,
    lyrics: [
      { id: 1, text: "Блёвбургер — это вам не гамбургер" },
      { id: 2, text: "Вялый хер, опиумная прослойка из мудей" },
      { id: 3, text: "Луговая тростинка, немного лука" },
      { id: 4, text: "Мука и хуй моржа, за место кунжута — анаша" },
    ],
    hintLineIds: [1],
    revealLineIds: [2, 3, 4],
  },
  {
    id: 12,
    title: "Черная дыра",
    url: "https://youtu.be/XshcPNtDn-U",
    start: 86.5,
    end: 98.5,
    lyrics: [
      { id: 1, text: "На Марсе небо голубое — очень серьёзная хуйня" },
      { id: 2, text: "Это не транслируется на станции" },
      { id: 3, text: "Ебалась, как Констанция с Д'Артаньяном" },
      { id: 4, text: "А мы тут припёрлись с кальяном" },
      { id: 5, text: "Сука, давай не базарь! Полёт нормальный" },
      { id: 6, text: "У космонавта отсосал инопланетянин" },
      { id: 7, text: "Поймал сигналы, два раза в жопу даже дал он" },
    ],
    hintLineIds: [1, 2, 3, 4, 5],
    revealLineIds: [6, 7],
  },
  {
    id: 13,
    title: "Короткая песенка",
    url: "https://youtu.be/qb0iDe1ppTw",
    start: 36,
    end: 45,
    lyrics: [
      { id: 1, text: "Яичница из одного яйца" },
      { id: 2, text: "Или как поймали с поличным твоего отца" },
      { id: 3, text: "Нет наличных, пацан" },
      { id: 4, text: "В метро через куртку сам себя помацал" },
      { id: 5, text: "Это тоже самое, что учить слепого ебаться" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 14,
    title: "Демоны",
    url: "https://youtu.be/Yoxy3ki35hc?list=OLAK5uy_k4kXEhcPSUcYFxTSxJJQtPgIBnNQtmfMc",
    start: 35,
    end: 39.5,
    lyrics: [
      { id: 1, text: "Летучая мышь летит на север" },
      { id: 2, text: "А мы такие с концертиком тут" },
      { id: 3, text: "Черти рисуют пентаграммы на членах" },
      { id: 4, text: "Захватил в заложники в Набережных Челнах" },
    ],
    hintLineIds: [1, 2],
    revealLineIds: [3, 4],
  },
];