import type { Round } from "../../types";

/** Все раунды викторины. Аудио — `public/content/audio/music/` (предпочтительно AAC .m4a). Фон — путь от `public/content/video/` (например `bg/…`). */
export const rounds: Round[] = [
  {
    id: 1,
    title: "Черная дыра",
    audioFile: "chernaya-dyra-a97c7b46.m4a",
    start: 21,
    end: 30.25,
    lyrics: [
      { id: 1, text: "Стебусь над школьницами, это заводит" },
      { id: 2, text: "Представляю чётко, чем всё это кончится" },
      { id: 3, text: "Как моя ракетница входит в твоё депо" },
      { id: 4, text: "Здесь только два варианта" },
      { id: 5, text: "Откуда в жопе бриллианты?" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 2,
    title: "В аквапарке",
    audioFile: "v-akvaparke-b33301b7.m4a",
    start: 23,
    end: 29,
    lyrics: [
      { id: 1, text: "В аквапарке реально охуенно, реально охуенно" },
      { id: 2, text: "Ну реально правда охуенно" },
      { id: 3, text: "В аквапарке горки, джакузи, ванны и фонтан" },
      { id: 4, text: "С детьми были там вчера" },
    ],
    hintLineIds: [1, 2],
    revealLineIds: [3, 4],
  },
  {
    id: 3,
    title: "Ебу закон",
    audioFile: "ebu-zakon-69cd5658.m4a",
    start: 12,
    end: 20.5,
    lyrics: [
      { id: 1, text: "С мусорами разговариваю шёпотом" },
      { id: 2, text: "Некий Урал достаёт из карманов что-то" },
      { id: 3, text: "За шторой гусёк суёт девке гондон свой" },
      { id: 4, text: "Я снова заснул с Олей, а проснулся с Колей" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 4,
    title: "Ебу закон",
    audioFile: "ebu-zakon-69cd5658.m4a",
    start: 34.5,
    end: 45.5,
    lyrics: [
      { id: 1, text: "Здесь играет биток, но не слышно басок" },
      { id: 2, text: "Косяк засох" },
      { id: 3, text: "Уральский насвай сплёвывает Васёк." },
      { id: 4, text: "На кассете Некий" },
      { id: 5, text: "Тут Кальмар ковыряется в заднем отсеке." },
      { id: 6, text: "Техник Паша - гомосек" },
    ],
    hintLineIds: [1, 2, 3, 4, 5],
    revealLineIds: [6],
  },
  {
    id: 5,
    title: "Море или океан",
    audioFile: "more-ili-okean-92ad9d39.m4a",
    start: 109.5,
    end: 119,
    lyrics: [
      { id: 1, text: "Тебе придется расстаться с паспортом" },
      { id: 2, text: "Сейчас не плохо бы просто здесь остаться" },
      { id: 3, text: "Ну а что потом? Потом снова в сонное царство!" },
      { id: 4, text: "На столе явства" },
      { id: 5, text: "У меня не встал на тебя, хотя я даже не в мясо" },
      { id: 6, text: "Просто чё-то барахлит с возрастом колбаса" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5, 6],
  },
  {
    id: 6,
    title: "Гитлер",
    audioFile: "gitler-18b67f8a.m4a",
    start: 81.5,
    end: 89.5,
    lyrics: [
      { id: 1, text: "Сходу соснул у паралимпийца" },
      { id: 2, text: "Старичок засунул кулак в анус" },
      { id: 3, text: "По гробам хуём баунс" },
      { id: 4, text: "Половая губа шепчет: «Трахай»" },
      { id: 5, text: "Хорватия, хватит ебать страусов" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 7,
    title: "Это жизнь",
    audioFile: "eto-zhizn-02a7de08.m4a",
    start: 3,
    end: 6,
    lyrics: [
      { id: 1, text: "Куча пенисов упирается мне в лицо" },
      { id: 2, text: "Я не вижу где яйца, но лижу мошонку" },
      { id: 3, text: "Его семя как сгущёнка" },
      { id: 4, text: "Да похуй" },
      { id: 5, text: "Прыгай в моё лоно" },
      { id: 6, text: "Пиздатое порно, рвутся гандоны" },
    ],
    hintLineIds: [1],
    revealLineIds: [2, 3, 4, 5, 6],
  },
  {
    id: 8,
    title: "Не прут колеса",
    audioFile: "ne-prut-kolesa-86d5711e.m4a",
    backgroundVideo: {
      file: "bg/bg_round_8.mp4",
      start: 84,
    },
    start: 27,
    end: 37,
    lyrics: [
      { id: 1, text: "У коровы есть вымя, не доёбывай меня" },
      { id: 2, text: "Большой хуй у коня (Что?)" },
      { id: 3, text: "У меня конечно поменьше" },
      { id: 4, text: "Я ебал не много женщин" },
      { id: 5, text: "Точнее шесть, не больше и не меньше" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 9,
    title: "За кем стоит андеграунд",
    audioFile: "za-kem-stoit-andergraund-1456eda1.m4a",
    backgroundVideo: {
      file: "bg/bg_round_9.mp4",
      start: 30,
    },
    start: 54.5,
    end: 61.5,
    lyrics: [
      { id: 1, text: "Меня от соли накрыло" },
      { id: 2, text: "Меня от соли накрыло" },
      { id: 3, text: "Я с Лефортово" },
      { id: 4, text: "У меня вот до сюда шорты" },
      { id: 5, text: "Если выше, то пидор" },
      { id: 6, text: "Если ниже, то гнида" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4, 5, 6],
  },
  {
    id: 10,
    title: "Заебись",
    audioFile: "zaebis-4e8375f7.m4a",
    start: 77,
    end: 85,
    lyrics: [
      { id: 1, text: "Я как будто кит, тебя оплодотворяю под этот хит" },
      { id: 2, text: "У меня пакет, в нем пачка оптимы и кент" },
      { id: 3, text: "Заваривай, блядина, горит резина" },
      { id: 4, text: "Мент пытался отъебать гориллу" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 11,
    title: "Блевбургер",
    audioFile: "blevburger-e34fa2a8.m4a",
    start: 0,
    end: 3.5,
    lyrics: [
      { id: 1, text: "Блёвбургер — это вам не гамбургер" },
      { id: 2, text: "Вялый хер, опиумная прослойка из мудей" },
      { id: 3, text: "Луговая тростинка, немного лука" },
      { id: 4, text: "Мука и хуй моржа, за место кунжута — анаша" },
    ],
    hintLineIds: [1],
    revealLineIds: [2, 3, 4],
  },
  {
    id: 12,
    title: "Черная дыра",
    audioFile: "chernaya-dyra-a97c7b46.m4a",
    start: 86.5,
    end: 98.5,
    lyrics: [
      { id: 1, text: "На Марсе небо голубое — очень серьёзная хуйня" },
      { id: 2, text: "Это не транслируется на станции" },
      { id: 3, text: "Ебалась, как Констанция с Д'Артаньяном" },
      { id: 4, text: "А мы тут припёрлись с кальяном" },
      { id: 5, text: "Сука, давай не базарь! Полёт нормальный" },
      { id: 6, text: "У космонавта отсосал инопланетянин" },
      { id: 7, text: "Поймал сигналы, два раза в жопу даже дал он" },
    ],
    hintLineIds: [1, 2, 3, 4, 5],
    revealLineIds: [6, 7],
  },
  {
    id: 13,
    title: "Короткая песенка",
    audioFile: "korotkaya-pesenka-e599d29b.m4a",
    start: 36,
    end: 45,
    lyrics: [
      { id: 1, text: "Яичница из одного яйца" },
      { id: 2, text: "Или как поймали с поличным твоего отца" },
      { id: 3, text: "Нет наличных, пацан" },
      { id: 4, text: "В метро через куртку сам себя помацал" },
      { id: 5, text: "Это тоже самое, что учить слепого ебаться" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 14,
    title: "Демоны",
    audioFile: "demony-79a26b8a.m4a",
    start: 35,
    end: 39.5,
    lyrics: [
      { id: 1, text: "Летучая мышь летит на север" },
      { id: 2, text: "А мы такие с концертиком тут" },
      { id: 3, text: "Черти рисуют пентаграммы на членах" },
      { id: 4, text: "Захватил в заложники в Набережных Челнах" },
    ],
    hintLineIds: [1, 2],
    revealLineIds: [3, 4],
  },
  {
    id: 15,
    title: "Лошок",
    audioFile: "27-loshok-d0490c0d.m4a",
    start: 53.61,
    end: 64.59,
    lyrics: [
      { id: 1, text: "Мы говорим по телефону рифмами из частушек" },
      { id: 2, text: "И не надо кушать китайскую лапшу и суши" },
      { id: 3, text: "От перца меня сушит, от водки гнёт" },
      { id: 4, text: "Но чтобы полегчало смотрю фотки её" },
      { id: 5, text: "А её колготки сейчас на мне" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 16,
    title: "Кассир",
    audioFile: "16-kassir-7f67a51a.m4a",
    start: 117.12,
    end: 123.92,
    lyrics: [
      { id: 1, text: "Извращенцы знают своих в лицо" },
      { id: 2, text: "Они поднимают настроение" },
      { id: 3, text: "Щупая друг друга за яйцо" },
      { id: 4, text: "Несет дерьмицом повсюду" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 17,
    title: "Тубик",
    audioFile: "tubik-60f6d765.m4a",
    start: 140.62,
    end: 147.25,
    lyrics: [
      { id: 1, text: "Хочу приготовить тебя, как мясо" },
      { id: 2, text: "Красиво и без пафоса" },
      { id: 3, text: "Будь как родная, или проваливай" },
      { id: 4, text: "Жалко в жопу мало давала до меня" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 18,
    title: "История короче длинная",
    audioFile: "23-istoriya-koroche-dlinnaya-7f421864.m4a",
    start: 144.77,
    end: 155.4,
    lyrics: [
      { id: 1, text: "Я короче вахуе от всего, иду на мазок" },
      { id: 2, text: "Потом к кожнику, к венерологу направили потом" },
      { id: 3, text: "На другую станцию" },
      { id: 4, text: "Или на трамвае около часа езды" },
      { id: 5, text: "Уже вечерком чуть не дали пизды чурки" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 19,
    title: "Ахуенно кого-нибудь убить",
    audioFile: "02-ahuenno-kogo-nibud-ubit-feat-the-chemodan-clan-1dbc8735.m4a",
    start: 104.63,
    end: 113.11,
    lyrics: [
      { id: 1, text: "Дежурный пальцем телефонный шнур держит" },
      { id: 2, text: "В голове у звонящего першит" },
      { id: 3, text: "И его сушит" },
      { id: 4, text: "А утром, когда он на Porsсhe, по радио" },
      { id: 5, text: "Признаюсь, я не морж, но в пруду купаюсь тоже" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 20,
    title: "Спасает параноя",
    audioFile: "18-spasaet-paranoya-f6aa067f.m4a",
    start: 163.07,
    end: 171.38,
    lyrics: [
      { id: 1, text: "Мой горизонт продвинут дальше, чем ваш" },
      { id: 2, text: "Глубокий водолаз нырнул" },
      { id: 3, text: "Изучаю космос, книги" },
      { id: 4, text: "Чай пью литрами" },
      { id: 5, text: "В голове одни алгоритмы и дифференциалы" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 21,
    title: "5 Лет",
    audioFile: "09-5-let-9cd4846f.m4a",
    start: 85.15,
    end: 92.96,
    lyrics: [
      { id: 1, text: "Лучше не суйся сюда, а то унесут в чёрном пакете тебя" },
      { id: 2, text: "Прошёл день. Я всё забыл" },
      { id: 3, text: "Едем в Киев, по пути пару дебилов кинули" },
      { id: 4, text: "Оказались тёлками, вернее, тётками" },
      { id: 5, text: "Им за сорок, ёмаё!" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4, 5],
  },
  {
    id: 22,
    title: "В Гавно",
    audioFile: "03-v-gavno-92d0bac6.m4a",
    start: 197.18,
    end: 204.77,
    lyrics: [
      { id: 1, text: "Шишки мне замутил Акиф, пью кефир" },
      { id: 2, text: "Но уже не помогает, рэп уже не вставляет" },
      { id: 3, text: "В больнице меня заставляют пить лекарства" },
      { id: 4, text: "И делать клизмы, а на зоне, суки, поили чифиром" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 23,
    title: "Пиской Трясёт",
    audioFile: "07-piskoi-tryase-t-2ea59f23.m4a",
    start: 39.16,
    end: 44.42,
    lyrics: [
      { id: 1, text: "Это всего лишь одна дорога быстрого" },
      { id: 2, text: "Мчусь по трасе" },
      { id: 3, text: "Его трясёт в экстазе" },
      { id: 4, text: "Первое сентября - новая пора учёба, ёбаный в рот, бля" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 24,
    title: "Клитор",
    audioFile: "22-klitor-93ecb072.m4a",
    start: 169.73,
    end: 180.87,
    lyrics: [
      { id: 1, text: "Узнай у неё, как лучше" },
      { id: 2, text: "Номер три — каждая женщина уникальна" },
      { id: 3, text: "Поэтому будет лучше, если ты поинтересуешься у неё" },
      { id: 4, text: "Какие ласки больше нравятся" },
      { id: 5, text: "От этого оба только выиграете" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 25,
    title: "Буду хулиганом",
    audioFile: "16-budu-huliganom-feat-iosan-massa-danya-sharap-2a09ad9a.m4a",
    start: 203.2,
    end: 214.6,
    lyrics: [
      { id: 1, text: "Вино пролили на линолеум" },
      { id: 2, text: "Почти 15 лет прошло с миллениума" },
      { id: 3, text: "Достаю коврик, встаю на колени" },
      { id: 4, text: "Взрывная волна ударяется в центр Майями" },
      { id: 5, text: "Янки заебывают" },
      { id: 6, text: "Хохлы жгут покрышки во Львове" },
    ],
    hintLineIds: [1, 2, 3, 4, 5],
    revealLineIds: [6],
  },
  {
    id: 26,
    title: "18:45:54",
    audioFile: "07-184554-eb81ccd3.m4a",
    start: 86.14,
    end: 96.4,
    lyrics: [
      { id: 1, text: "Это миссия невыполнима, прессованная полынь" },
      { id: 2, text: "Сыплю мимо, ух нихуя от спайсика нормально накурило" },
      { id: 3, text: "Где мои ножнички? Твои ножки на плечах расставлены правильно" },
      { id: 4, text: "Взаимодействие с родителями, как с полицией" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 27,
    title: "Пидерсии ",
    audioFile: "21-pidersii-feat-slimus-sladkoezhka-rjb-larik-surapov-e71de63c.m4a",
    start: 5.12,
    end: 15.5,
    lyrics: [
      { id: 1, text: "Анальные мази, бездарные мрази" },
      { id: 2, text: "Связи, базы данных, волосы-пазлы" },
      { id: 3, text: "Козлы те, кто лазит" },
      { id: 4, text: "Но не понимает мазы, опасны не мы" },
      { id: 5, text: "А вы опасны, пидарасы" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 28,
    title: "Руны",
    audioFile: "04-runy-feat-mc-kalmar-79561da0.m4a",
    start: 152.3,
    end: 159,
    lyrics: [
      { id: 1, text: "Стрелок с кутузовской" },
      { id: 2, text: "Кузьминский лох" },
      { id: 3, text: "Бабушкинский сынок" },
      { id: 4, text: "Лефортовский маньяк" },
      { id: 5, text: "По щам я за-ме-тил что ты гу-у-ук!" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 29,
    title: "Руны",
    audioFile: "04-runy-feat-mc-kalmar-79561da0.m4a",
    start: 182.4,
    end: 195.4,
    lyrics: [
      { id: 1, text: "Утром процесс, надеюсь, будет ждать меня принцесса" },
      { id: 2, text: "Если выпустят пораньше" },
      { id: 3, text: "Выступаем на парашном концерте" },
      { id: 4, text: "Ну, парни, я богат вашими респектами, сейчас уже на Гелике" },
      { id: 5, text: "А, не, не-не-не-не, просто нанюхался" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 30,
    title: "Сделал закладку",
    audioFile: "09-sdelal-zakladku-feat-dubbi-du-eb6fdca0.m4a",
    start: 75,
    end: 80.8,
    lyrics: [
      { id: 1, text: "Держи удар в душу, Коля" },
      { id: 2, text: "25 на 25 неподалёку от школы" },
      { id: 3, text: "Помню, играли гормоны" },
      { id: 4, text: "На прилавке наши альбомы. Купишь, или нахуй такое?" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 31,
    title: "Соли",
    audioFile: "15-soli-299f2f03.m4a",
    start: 130.58,
    end: 140.13,
    lyrics: [
      { id: 1, text: "Как Mix Fighter, разбивает бровь" },
      { id: 2, text: "Лошок в лесу нарывается на заражение микробами" },
      { id: 3, text: "Недавно ходили в порнуху на пробы, хотели устроиться" },
      { id: 4, text: "Кусает гашиш усатая Оля" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 32,
    title: "Ольга Марковна",
    audioFile: "12-olga-markovna-3e3f34a7.m4a",
    start: 131.7,
    end: 140.8,
    lyrics: [
      { id: 1, text: "Друг пишет, что в плену клинок вонзили в ногу" },
      { id: 2, text: "Это хачье, а мы White Power парни" },
      { id: 3, text: "Нам такой хуйни не надо" },
      { id: 4, text: "Ух как хорошо я пёрнул только что" },
      { id: 5, text: "А теперь давай прогоним Путина" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 33,
    title: "Побудь Со Мной",
    audioFile: "24-pobud-so-mnoi-2ef9e23c.m4a",
    start: 6.11,
    end: 12.1,
    lyrics: [
      { id: 1, text: "На меня напала грусть, но я за Русь" },
      { id: 2, text: "И слушаю Гуфа" },
      { id: 3, text: "Гуталином натёр туфли, потом к тебе иду" },
      { id: 4, text: "В ларьке покупаю букет двадцать белых роз" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 34,
    title: "Побудь Со Мной",
    audioFile: "24-pobud-so-mnoi-2ef9e23c.m4a",
    start: 94.7,
    end: 101.7,
    lyrics: [
      { id: 1, text: "Хоть она и чернокожая" },
      { id: 2, text: "Отлично сыграла на моей флейте кожаной" },
      { id: 3, text: "Я пижон в кожане" },
      { id: 4, text: "Когда изящно поёбываю тебя" },
      { id: 5, text: "Мой врунометр" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 35,
    title: "Гул Гул Гул",
    audioFile: "22-gul-gul-gul-1442c7fc.m4a",
    start: 137.55,
    end: 144.8,
    lyrics: [
      { id: 1, text: "И мужик надавив ляхой на колени оленем" },
      { id: 2, text: "На ладе калине едут за первым к Лене" },
      { id: 3, text: "Смотрю на портрет Ленина" },
      { id: 4, text: "Это год Есенина" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 36,
    title: "Мой Срок Кончается",
    audioFile: "12-moi-srok-konchaetsya-6f45d6a4.m4a",
    start: 70.42,
    end: 78.75,
    lyrics: [
      { id: 1, text: "Мой срок кончается в пятницу" },
      { id: 2, text: "Болезнь? Пей перепелиные яйца - пью" },
      { id: 3, text: "И белый нюхаю и закуриваю плюхой" },
      { id: 4, text: "Встать, суд идет, подсудимый-рэперок" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 37,
    title: "Хочешь быть сильным",
    audioFile: "kunteynir-ty-hochesh-byt-silnym-55b743b5.m4a",
    backgroundVideo: {
      file: "bg/wannabestrong.mp4",
      start: 20,
    },
    start: 51.53,
    end: 57.4,
    lyrics: [
      { id: 1, text: "А ты попал в даун-таун, прошла двушка — нокдаун" },
      { id: 2, text: "Девушка квакает под спайсом" },
      { id: 3, text: "А я ебу тебя через Нью-Йорк;" },
      { id: 4, text: "А он через неё, хуй с штанов достаёт" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 38,
    title: "Я ебал в рот",
    audioFile: "02-pasha-tehnik-ya-exxl-v-rot-prod-by-fd-vadim-b2889d77.m4a",
    backgroundVideo: {
      file: "bg/yaebal.mp4",
      start: 25,
    },
    start: 3.4,
    end: 4.9,
    lyrics: [
      { id: 1, text: "Я ебал в рот" },
      { id: 2, text: "Тех, кто не ебал в рот тех, кто ебал в жопу" },
    ],
    hintLineIds: [1],
    revealLineIds: [2],
  },
  {
    id: 39,
    title: "Спартанский жим",
    audioFile: "06-metox-pasha-tehnik-raskolnikov-spartanskii-zhim-551df03d.m4a",
    start: 198.8,
    end: 209.7,
    lyrics: [
      { id: 1, text: "Спартанский жим нагишом, мы делаем шоу" },
      { id: 2, text: "Янг Траппа далеко зашёл" },
      { id: 3, text: "Нам то это всё за шо? С нами Сашок" },
      { id: 4, text: "Мы на спорте будто бы выпускники СДЮСШОР" },
      { id: 5, text: "Если уж лев — против, то я тигр — за" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 40,
    title: "Нужен Xanax",
    audioFile: "06-pasha-tehnik-nuzhen-xanax-14ab85f2.m4a",
    backgroundVideo: {
      file: "bg/xanax.mp4",
      start: 35,
    },
    start: 33.3,
    end: 39.5,
    lyrics: [
      { id: 1, text: "Слава Кастору Трою" },
      { id: 2, text: "Одеялом теплым тебя накрою" },
      { id: 3, text: "Когда не пою, меня кроет" },
      { id: 4, text: "Обожаю мясо с кровью, кровью" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 41,
    title: "Гусь",
    audioFile: "kunteynir-gus-feat-feduk-music-channel-950fd62f.m4a",
    start: 149.1,
    end: 157.8,
    lyrics: [
      { id: 1, text: "И мы такие идём обниматься с бурятами" },
      { id: 2, text: "Вы короли, бля, е, да вы хуи, вы хуи" },
      { id: 3, text: "Хуи ебаные, мы ебали вашу маму вдвоём" },
      { id: 4, text: "Здесь в дипломатии нули" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 60,
    title: "Гусь",
    audioFile: "kunteynir-gus-feat-feduk-music-channel-950fd62f.m4a",
    start: 100.3,
    end: 107.4,
    lyrics: [
      { id: 1, text: "Е, или принимай в свой рот" },
      { id: 2, text: "Кожаную пулю, в чёрную жопу" },
      { id: 3, text: "Собирай мёд или выделения" },
      { id: 4, text: "В трусах — огород, покидаю отделение" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 42,
    title: "Гусь",
    audioFile: "kunteynir-gus-feat-feduk-music-channel-950fd62f.m4a",
    start: 72,
    end: 78.6,
    lyrics: [
      { id: 1, text: "На меня молились" },
      { id: 2, text: "Бисером шили на джинсовках моё имя" },
      { id: 3, text: "В восьмидесятые — игры, юго-запад" },
      { id: 4, text: "На докатке из татарской деревни едет назад" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 43,
    title: "Я люблю кататься на велике",
    audioFile: "pasha-ya-lyublyu-katatsya-na-velike-cbaa63bc.m4a",
    start: 12.01,
    end: 18.22,
    lyrics: [
      { id: 1, text: "Белая слива, смело съели" },
      { id: 2, text: "Дальше куда-то поехали" },
      { id: 3, text: "Я люблю кататься на велике" },
      { id: 4, text: "Как старина Хофман когда-то летом" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 44,
    title: "Криптоминетчица",
    audioFile: "metox-pasha-kriptominetchica-b0006214.m4a",
    start: 90.17,
    end: 98.8,
    lyrics: [
      { id: 1, text: "Если б вы пришли к ней — она б вам не давала" },
      { id: 2, text: "Меня замедлило, я будто бы коала" },
      { id: 3, text: "Передо мной на «ЧБД» на стуле сидел Дава" },
      { id: 4, text: "Значит ли это то, что я там законтачился?" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 46,
    title: "Колбаса",
    audioFile: "kolbasa-213c3bbb.m4a",
    start: 74,
    end: 77.5,
    lyrics: [
      { id: 1, text: "И что-то вылетело нахуй у этих парней из ануса" },
      { id: 2, text: "В упор стреляет человек без усов" },
      { id: 3, text: "Ездил на велике, как в детстве Кобзон" },
      { id: 4, text: "Потом мне не понравился бон, подрались" },
    ],
    hintLineIds: [1],
    revealLineIds: [2, 3, 4],
  },
  {
    id: 48,
    title: "4:20",
    audioFile: "kunteynir-4-20-9bd5a792.m4a",
    start: 102.7,
    end: 109,
    lyrics: [
      { id: 1, text: "Тут наказывают за пару парашютов" },
      { id: 2, text: "Шут прапорщик Ашот" },
      { id: 3, text: "Нюхни мой гребешок сержант Ершов" },
      { id: 4, text: "Это как трахаться с бомжом за рожок мороженного" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 49,
    title: "О том",
    audioFile: "kunteynir-o-tom-bcdff094.m4a",
    start: 208.7,
    end: 218.7,
    lyrics: [
      { id: 1, text: "Как в 11 лет тряпка и бензин" },
      { id: 2, text: "Как в 16 выпускной, в 20 лимузин" },
      { id: 3, text: "Грузин че-то за баранкой бузил" },
      { id: 4, text: "А я четко наебывал в свое время" },
      { id: 5, text: "Искал выгоду, как одесский еврей" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 50,
    title: "В трусах",
    audioFile: "kunteynir-v-trusah-166aa5ba.m4a",
    start: 30,
    end: 39.6,
    lyrics: [
      { id: 1, text: "Пиздатые на тачке ковши" },
      { id: 2, text: "Салон свиной кожей обшит" },
      { id: 3, text: "Нам по хуй, кто ты" },
      { id: 4, text: "Хоть Букин, хоть из «Касты» Шым" },
      { id: 5, text: "Я делаю в тренажёрке жим - Лёжа" },
      { id: 6, text: "А в это время меня страхует - Лёша" },
    ],
    hintLineIds: [1, 2, 3, 4, 5],
    revealLineIds: [6],
  },
  {
    id: 51,
    title: "Звезда",
    audioFile: "pasha-zvezda-e81ac4a6.m4a",
    start: 10.5,
    end: 18.9,
    lyrics: [
      { id: 1, text: "Ох, какие у меня красивый ноги" },
      { id: 2, text: "И поймут меня не многие" },
      { id: 3, text: "Но я не уебок" },
      { id: 4, text: "Я с хип хопом бок о бок" },
      { id: 5, text: "Поймет меня лишь Заги Бок" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 54,
    title: "Кассир во Fred Perry",
    audioFile: "kassir-vo-fred-perry-ff31e1e8.m4a",
    start: 113.4,
    end: 124.67,
    lyrics: [
      { id: 1, text: "Им не нужны кукуруза за щеку" },
      { id: 2, text: "Ломятся нищуки вдруг по ящику" },
      { id: 3, text: "Своими губами не по делу шуршат" },
      { id: 4, text: "Нынешняя молодежь решает, а хотя бы лет через 50 вернуться обратно" },
      { id: 5, text: "Как всё было культурно: никакого хип-хапа" },
    ],
    hintLineIds: [1, 2, 3, 4],
    revealLineIds: [5],
  },
  {
    id: 55,
    title: "Давай поговорим о футболе",
    audioFile: "kunteynir-davay-pogovorim-o-futbole-839c228c.m4a",
    start: 97.65,
    end: 104.36,
    lyrics: [
      { id: 1, text: "А поколение некст на всё положило с прибором" },
      { id: 2, text: "Прибраться в стране" },
      { id: 3, text: "Убрать лентяев и бездарей" },
      { id: 4, text: "Отбить кубок мира" },
      { id: 5, text: "Завоевать забытый трофей" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4, 5],
  },
  {
    id: 56,
    title: "Мент",
    audioFile: "kunteynir-ment-ea30719e.m4a",
    start: 100.8,
    end: 107.13,
    lyrics: [
      { id: 1, text: "Люблю порох, люблю пороть комаров" },
      { id: 2, text: "Это моя жизненная основа" },
      { id: 3, text: "Виски, кола, дело прокурора" },
      { id: 4, text: "Голову тупой стороной молота ударила круглая" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 57,
    title: "Сколько дыма…",
    audioFile: "kunteynir-skolko-dyma-d52677d4.m4a",
    start: 64,
    end: 68.53,
    lyrics: [
      { id: 1, text: "Сколько дыма влезет в наши лёгкие" },
      { id: 2, text: "Как осколки колкие" },
      { id: 3, text: "Мои мозги умирают от тоски" },
      { id: 4, text: "Есть тут кто-то? Да я есть тут!" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 58,
    title: "Шлягер",
    audioFile: "kunteynir-shlyager-61a0e6ec.m4a",
    start: 57.2,
    end: 66.72,
    lyrics: [
      { id: 1, text: "На что то надеюсь, чё-то поддуваюсь" },
      { id: 2, text: "Надеваю аляску, трубы, попадаю в сказку" },
      { id: 3, text: "Но паспорт с собой не беру, в нашем GPS сбои" },
      { id: 4, text: "Буш ты сраный ковбой, я за родной рубль" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
  {
    id: 59,
    title: "Всё включено",
    audioFile: "kunteynir-vsyo-vklyucheno-c8f226d4.m4a",
    start: 6.1,
    end: 11.8,
    lyrics: [
      { id: 1, text: "Пару партий в пул продул" },
      { id: 2, text: "Не хватило фил" },
      { id: 3, text: "Пока не словил пулю на жопу как улей" },
      { id: 4, text: "Азербайджанский chill" },
    ],
    hintLineIds: [1, 2, 3],
    revealLineIds: [4],
  },
];
